CREATE TABLE TST_CUSTOMERS 
(
  ID RAW(16) NOT NULL 
, TAX_ID VARCHAR2(20) 
, NICKNAME VARCHAR2(50) NOT NULL 
, FULL_NAME VARCHAR2(100) 
, EMAIL VARCHAR2(100) NOT NULL 
, LAST_ORDER_DATE TIMESTAMP 
, CREDIT_LIMIT NUMBER(15, 2) 
, CURRENT_BALANCE NUMBER(15, 2) 
, CREATED_AT TIMESTAMP 
, CREATED_BY VARCHAR2(100) 
, UPDATED_AT TIMESTAMP 
, UPDATED_BY VARCHAR2(100) 
, CONSTRAINT TST_CUSTOMERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE TST_PHONE_TYPES 
(
  ID RAW(16) NOT NULL 
, CODE VARCHAR2(5) NOT NULL 
, NAME VARCHAR2(50) NOT NULL 
, DESCRIPTION VARCHAR2(300) 
, CREATED_AT TIMESTAMP 
, CREATED_BY VARCHAR2(100) 
, UPDATED_AT TIMESTAMP 
, UPDATED_BY VARCHAR2(100) 
, CONSTRAINT TST_PHONE_TYPES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE TST_SALES_REPRESENTATIVE 
(
  ID RAW(16) NOT NULL 
, EMPLOYEE_CODE VARCHAR2(20) NOT NULL 
, TAX_ID VARCHAR2(20) 
, NICKNAME VARCHAR2(20) NOT NULL 
, FULL_NAME VARCHAR2(100) 
, EMAIL VARCHAR2(100) NOT NULL 
, CELL_PHONE VARCHAR2(50) NOT NULL 
, CREATED_AT TIMESTAMP 
, CREATED_BY VARCHAR2(100) 
, UPDATED_AT TIMESTAMP 
, UPDATED_BY VARCHAR2(100) 
, CONSTRAINT TST_SALES_REPRESENTATIVE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE TST_CUSTOMER_PHONES 
(
  ID RAW(16) NOT NULL 
, CUSTOMER_ID RAW(16) NOT NULL 
, PHONE_TYPE_ID RAW(16) NOT NULL 
, DDI NUMBER(5) 
, DDD NUMBER(5) NOT NULL 
, PHONE_NUMBER VARCHAR2(30) NOT NULL 
, NOTES VARCHAR2(300) 
, CREATED_AT TIMESTAMP 
, CREATED_BY VARCHAR2(100) 
, UPDATED_AT TIMESTAMP 
, UPDATED_BY VARCHAR2(100) 
, CONSTRAINT TST_CUSTOMER_PHONES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE TST_ORDERS 
(
  ID RAW(16) NOT NULL 
, CUSTOMER_ID RAW(16) NOT NULL 
, SALES_REPRESENTATIVE_ID RAW(16) NOT NULL 
, ORDER_NRO VARCHAR2(50) 
, ORDER_DATE TIMESTAMP 
, ORDER_VALUE NUMBER(15, 2) 
, PAID_AMOUNT NUMBER(15, 2) 
, COMMISSION_RATE NUMBER(5, 2) 
, NOTES VARCHAR2(300) 
, CREATED_AT TIMESTAMP 
, CREATED_BY VARCHAR2(100) 
, UPDATED_AT TIMESTAMP 
, UPDATED_BY VARCHAR2(100) 
, CONSTRAINT TST_ORDERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE INDEX TST_CUSTOMERS_INDEX1 ON TST_CUSTOMERS (TAX_ID ASC);

CREATE INDEX TST_CUSTOMERS_INDEX2 ON TST_CUSTOMERS (NICKNAME ASC);

CREATE INDEX TST_CUSTOMER_PHONES_INDEX1 ON TST_CUSTOMER_PHONES (CUSTOMER_ID ASC);

CREATE INDEX TST_CUSTOMER_PHONES_INDEX2 ON TST_CUSTOMER_PHONES (PHONE_TYPE_ID ASC);

CREATE INDEX TST_CUSTOMER_PHONES_INDEX3 ON TST_CUSTOMER_PHONES (PHONE_NUMBER ASC);

CREATE INDEX TST_ORDERS_INDEX1 ON TST_ORDERS (CUSTOMER_ID ASC);

CREATE INDEX TST_ORDERS_INDEX2 ON TST_ORDERS (SALES_REPRESENTATIVE_ID ASC);

CREATE INDEX TST_ORDERS_INDEX3 ON TST_ORDERS (ORDER_DATE DESC);

ALTER TABLE TST_CUSTOMERS
ADD CONSTRAINT TST_CUSTOMERS_UK1 UNIQUE 
(
  EMAIL 
)
ENABLE;

ALTER TABLE TST_CUSTOMER_PHONES
ADD CONSTRAINT TST_CUSTOMER_PHONES_UK1 UNIQUE 
(
  CUSTOMER_ID 
, PHONE_TYPE_ID 
, DDI 
, DDD 
, PHONE_NUMBER 
)
ENABLE;

ALTER TABLE TST_ORDERS
ADD CONSTRAINT TST_ORDERS_UK1 UNIQUE 
(
  ORDER_NRO 
)
ENABLE;

ALTER TABLE TST_PHONE_TYPES
ADD CONSTRAINT TST_PHONE_TYPES_UK1 UNIQUE 
(
  CODE 
)
ENABLE;

ALTER TABLE TST_PHONE_TYPES
ADD CONSTRAINT TST_PHONE_TYPES_UK2 UNIQUE 
(
  NAME 
)
ENABLE;

ALTER TABLE TST_CUSTOMER_PHONES
ADD CONSTRAINT TST_CUSTOMER_PHONES_FK1 FOREIGN KEY
(
  PHONE_TYPE_ID 
)
REFERENCES TST_PHONE_TYPES
(
  ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE TST_CUSTOMER_PHONES
ADD CONSTRAINT TST_CUSTOMER_PHONES_FK2 FOREIGN KEY
(
  CUSTOMER_ID 
)
REFERENCES TST_CUSTOMERS
(
  ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE TST_ORDERS
ADD CONSTRAINT TST_ORDERS_FK1 FOREIGN KEY
(
  SALES_REPRESENTATIVE_ID 
)
REFERENCES TST_SALES_REPRESENTATIVE
(
  ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE TST_ORDERS
ADD CONSTRAINT TST_ORDERS_TS_CUSTOMERS_FK1 FOREIGN KEY
(
  CUSTOMER_ID 
)
REFERENCES TST_CUSTOMERS
(
  ID 
)
ON DELETE SET NULL ENABLE;

CREATE TRIGGER TST_CUSTOMERS_T 
BEFORE DELETE OR INSERT OR UPDATE ON TST_CUSTOMERS 
FOR EACH ROW
BEGIN
    IF INSERTING THEN
    
        IF :NEW.ID IS NULL THEN
            :NEW.ID := SYS_GUID();
        END IF;

        IF :NEW.CREATED_BY IS NULL THEN        
            :NEW.CREATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
        END IF;
        
        IF :NEW.UPDATED_BY IS NULL THEN        
            :NEW.UPDATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
        END IF;
        
        :NEW.CREATED_AT := SYSTIMESTAMP;
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
  
    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
        :NEW.UPDATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
    END IF;
END;
/

CREATE TRIGGER TST_CUSTOMER_PHONES_T 
BEFORE DELETE OR INSERT OR UPDATE ON TST_CUSTOMER_PHONES 
FOR EACH ROW
BEGIN
    IF INSERTING THEN
    
        IF :NEW.ID IS NULL THEN
            :NEW.ID := SYS_GUID();
        END IF;

        IF :NEW.CREATED_BY IS NULL THEN        
            :NEW.CREATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
        END IF;
        
        IF :NEW.UPDATED_BY IS NULL THEN        
            :NEW.UPDATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
        END IF;
        
        :NEW.CREATED_AT := SYSTIMESTAMP;
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
  
    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
        :NEW.UPDATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
    END IF;
END;
/

CREATE TRIGGER TST_ORDERS_T 
BEFORE DELETE OR INSERT OR UPDATE ON TST_ORDERS 
FOR EACH ROW
BEGIN
    IF INSERTING THEN
    
        IF :NEW.ID IS NULL THEN
            :NEW.ID := SYS_GUID();
        END IF;

        IF :NEW.CREATED_BY IS NULL THEN        
            :NEW.CREATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
        END IF;
        
        IF :NEW.UPDATED_BY IS NULL THEN        
            :NEW.UPDATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
        END IF;
        
        :NEW.CREATED_AT := SYSTIMESTAMP;
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
  
    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
        :NEW.UPDATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
    END IF;
END;
/

CREATE TRIGGER TST_PHONE_TYPES_T 
BEFORE DELETE OR INSERT OR UPDATE ON TST_PHONE_TYPES 
FOR EACH ROW
BEGIN
    IF INSERTING THEN
    
        IF :NEW.ID IS NULL THEN
            :NEW.ID := SYS_GUID();
        END IF;

        IF :NEW.CREATED_BY IS NULL THEN        
            :NEW.CREATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
        END IF;
        
        IF :NEW.UPDATED_BY IS NULL THEN        
            :NEW.UPDATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
        END IF;
        
        :NEW.CREATED_AT := SYSTIMESTAMP;
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
  
    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
        :NEW.UPDATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
    END IF;
END;
/

CREATE TRIGGER TST_SALES_REPRESENTATIVE_T 
BEFORE DELETE OR INSERT OR UPDATE ON TST_SALES_REPRESENTATIVE 
FOR EACH ROW
BEGIN
    IF INSERTING THEN
    
        IF :NEW.ID IS NULL THEN
            :NEW.ID := SYS_GUID();
        END IF;

        IF :NEW.CREATED_BY IS NULL THEN        
            :NEW.CREATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
        END IF;
        
        IF :NEW.UPDATED_BY IS NULL THEN        
            :NEW.UPDATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
        END IF;
        
        :NEW.CREATED_AT := SYSTIMESTAMP;
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
  
    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
        :NEW.UPDATED_BY := APEX_UTIL.GET_SESSION_STATE('APP_USER');
    END IF;
END;
/
